spring.application.name=studentapp
spring.datasource.url=jdbc:mysql://localhost:3306/studentdb
spring.datasource.username=root
spring.datasource.password=kiit

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true